require: rubocop-performance

inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - "db/migrate/**/*"
    - "db/schema.rb"
    - "vendor/**/*"
    - "spec/spec_helper.rb"
    - "spec/rails_helper.rb"
    - "bin/**/*"
    - "Gemfile"
    - "config/routes.rb"
    - "node_modules/**/*"
