language: ruby
services:
  - postgresql
cache: bundler
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rails db:create db:migrate
script:
  - bundle exec rails test
notifications:
  email: false
