version: "3"
services:
  db:
    image: postgres:11-alpine
    ports:
      - "15432:5432"
  web:
    build: .
    command: bundle exec puma
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
