version: "3"
services:
  db:
    image: postgres:11-alpine
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
  web:
    build: .
    command: bundle exec puma
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_HOST: db
    depends_on:
      - db
