version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run: docker-compose build
      - run: docker-compose up -d
      - run: sleep 1
      - run: docker-compose run web rails db:create db:schema:load
      - run: docker-compose run web rubocop
      - run: docker-compose run web rspec spec
      - run: docker-compose down
