version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run: docker-compose build
      - run: docker-compose up -d
      - run: sleep 1
      - run: docker-compose run backend rails db:create db:schema:load
      - run: docker-compose run backend rubocop
      - run: docker-compose run backend rspec spec
      - run: docker-compose down
