name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{matrix.ruby}}
    strategy:
      matrix:
        ruby: [2.7, 2.6]
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependent libralies
        run: sudo apt-get install libpq-dev

      - name: Build and test with rspec
        run: |
          bundle update --bundler
          bundle install --jobs 4 --retry 3
          cp config/database.yml.travis config/database.yml
          bundle exec rails c -e test
          bundle exec rails db:create db:schema:load
          bundle exec rubocop
          bundle exec rspec --format progress --out /tmp/rspec.xml spec
