name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "11" # See https://hub.docker.com/_/postgres for available versions

      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x

      - name: Build and test with Rake
        run: |
          bundle install --jobs 4 --retry 3
          cp config/database.yml.travis config/database.yml
          bundle exec rails db:create db:schema:load
          bundle exec rubocop
          bundle exec rspec --format progress --out /tmp/rspec.xml spec
